gssi:
	git rm ../_papers/gssi_*
	python3 importgssi.py
	git add ../papers/gssi_*
	git commit -am "gssi bib updated"
	git push

imt:
	git rm ../_papers/imt_*
	python3 importimt.py
	git add ../papers/imt_*
	git commit -am "imt bib updated"
	git push

isti:
	git rm ../_papers/isti_*
	python3 importisti.py
	git add ../papers/isti_*
	git commit -am "isti bib updated"
	git push

unicam:
	git rm ../_papers/unicam_*
	python3 importunicam.py
	git add ../papers/unicam_*
	git commit -am "unicam bib updated"
	git push

unipi:
	git rm ../_papers/unipi_*
	python3 importunipi.py
	git add ../papers/unipi_*
	git commit -am "unipi bib updated"
	git push

uniud:
	git rm ../_papers/uniud_*
	python3 importuniud.py
	git add ../papers/uniud_*
	git commit -am "uniud bib updated"
	git push

test:
	git rm ../_papers/test_*
	python3 importtest.py
	git add ../papers/test_*
	git commit -am "test bib updated"
	git push
	@echo("test updated")

